### PR TITLE
Remove locale deduction and path matching from history builder

### PR DESCRIPTION
**Pull request by camertron**
Deducing locales from paths and translation path matching has been moved to core. All credit goes to @zvkemp for this one :)

/cc @lumoslabs/platform

### CODE REVIEW

**Comment by seunghyo** [comment]
can i get some more context on this change?

**Comment by camertron** [comment]
Of course :)

When we want to add another repository to Rosette, say LumosityAndroid, we'd like to also import all the phrase and translation history into our database. History comes in the form of commits. Any phrases found in `values/strings.xml` and any translations found in `values-ja/strings.xml` will be parsed and imported.

Historically we only really had code to do this for Rails projects. There was a `RailsTranslationHistoryBuilder` in rosette-core as well as a `RailsPathMatcher` in lumos-rosette/server (in scripts/build_history.rb). Rather than keep creating custom path matchers and history builders, we decided instead to make path matching part of the configuration you write when adding a repo to Rosette. This PR encapsulates the minor changes that need to happen in the general-purpose translation history builder script. Instead of passing in a path matcher via the options hash, `build_translation_history.rb` expects the repo config to know how to recognize paths that contain translations as well as deduce the locale any given path represents.

**Comment by seunghyo** [comment]
okay that makes a lot of sense. so i'm assuming that in the repo config, `add_translation_path_matcher` allows `get_translation_path_matcher` to forward the right call as would `locale_from_path` to `deduce_locale_from_path`? i'm comparing the android diff to what we've added here.

**Comment by camertron** [comment]
Yes, that's correct :)

**Comment by seunghyo** [comment]
tight! :moyai: 

the android PR is fine too  :articulated_lorry:

**Pull request merged**
